server:
  port: 8511 #端口号

spring:
  application:
    name: service-product #服务名
  datasource: #MySQL数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spzx?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  data:
    redis: #Redis数据库连接
      host: localhost
      port: 6379
  jackson: #json时间的时区-响应给前端的数据
    time-zone: Asia/Shanghai
  cloud:
    nacos:
      discovery: #nacos注册中心的地址
        server-addr: localhost:8848


mybatis: #MyBatis配置
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*/*.xml